<?xml version="1.0" encoding="utf-8"?><Database Name="ShukudoProject" Class="DataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC\SQLEXPRESS;Initial Catalog=ShukudoProject;Integrated Security=True" SettingsObjectName="DAL.Shokudo.Properties.Settings" SettingsPropertyName="ShukudoProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Request" Member="Requests">
    <Type Name="Request">
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Value" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_Request" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Client_Request" Member="Client" ThisKey="ClientID" OtherKey="ClientID" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Login" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Administrator" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Request" Member="Requests" ThisKey="UserID" OtherKey="UserID" Type="Request" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Cell" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Client_Request" Member="Requests" ThisKey="ClientID" OtherKey="ClientID" Type="Request" />
    </Type>
  </Table>
</Database>